name: 'Polo.Dashboard.WebApi'
on:
 push:
    branches:
      - homologation
 pull_request:
    branches:
      - homologation
jobs:
 build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Set Dotnet"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: "Restore dependencies"
      run: dotnet restore Polo.Dashboard.WebApi/Polo.Dashboard.WebApi.csproj
    - name: "Build api"
      run: dotnet build Polo.Dashboard.WebApi/Polo.Dashboard.WebApi.csproj --configuration Release
 test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Set Dotnet"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: "Restore dependencies"
      run: dotnet restore Polo.Dashboard.WebApi.Tests/Polo.Dashboard.WebApi.Tests.csproj
    - name: "Run unit test"
      run: dotnet test Polo.Dashboard.WebApi.Tests/Polo.Dashboard.WebApi.Tests.csproj --verbosity normal
 deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
           service-id: ${{ secrets.RENDER_SERVICE_ID }}
           api-key: ${{ secrets.RENDER_API_KEY }}
